[workspace]
members = [
    "core",
    "chain/common",
    "chain/ethereum",
    "graphql",
    "mock",
    "node",
    "runtime/wasm",
    "runtime/derive",
    "server/http",
    "server/json-rpc",
    "server/index-node",
    "server/metrics",
    "store/postgres",
    "store/test-store",
    "graph",
]
