[package]
name = "graph-chain-ethereum"
version = "0.17.0"
edition = "2018"

[dependencies]
chrono = "0.4"
failure = "0.1.6"
futures = "0.1.21"
hex-literal = "0.2"
jsonrpc-core = "13.2.0"
graph = { path = "../../graph" }
graph-chain-common = { path = "../common" }
lazy_static = "1.2.0"
mock = { package = "graph-mock", path = "../../mock" }
state_machine_future = "0.2"

[dev-dependencies]
diesel = { version = "1.4.2", features = ["postgres", "serde_json", "numeric", "r2d2"] }
mockall = "0.5.0"
graph-core = { path = "../../core" }
graph-store-postgres = { path = "../../store/postgres" }
pretty_assertions = "0.6.1"
test-store = { path = "../../store/test-store" }
