[package]
name = "graph-chain-ethereum"
version = "0.17.1"
edition = "2018"

[dependencies]
async-trait = "0.1.25"
chrono = "0.4"
failure = "0.1.7"
futures = { package = "futures", version="0.1.29" }
jsonrpc-core = "14.0.5"
graph = { path = "../../graph" }
graph-core = { path = "../../core" }
graph-runtime-wasm = { path = "../../runtime/wasm" }
mock = { package = "graph-mock", path = "../../mock" }
lazy_static = "1.2.0"
hex-literal = "0.2"
state_machine_future = "0.2"
uuid = { version = "0.8.1", features = ["v4"] }
wasmi = "0.5.1"

[dev-dependencies]
diesel = { version = "1.4.2", features = ["postgres", "serde_json", "numeric", "r2d2"] }
mockall = "0.6.0"
graph-core = { path = "../../core" }
graph-store-postgres = { path = "../../store/postgres" }
pretty_assertions = "0.6.1"
test-store = { path = "../../store/test-store" }
